In [59]:
import random as rd
import numpy as np
class Pessoa:
    def __init__(self):
        self.atributos=[]
        Rendimento_mensal=[0.044, 0.185, 0.359, 0.187, 0.116, 0.053, 0.055]
        cv_Rendimento_mensal=[0.17, 0.088, 0.067, 0.093, 0.118, 0.173, 0.172]
        for i in range(len(cv_Rendimento_mensal)):
            Rendimento_mensal[i]=Rendimento_mensal[i]+rd.uniform(-cv_Rendimento_mensal[i]*Rendimento_mensal[i],cv_Rendimento_mensal[i]*Rendimento_mensal[i])
        a=np.random.multinomial(1,Rendimento_mensal)
        if a[0]==1:
            self.atributos.append("Sem rendimento a 1/2 salário mínimo")
        elif a[1]==1:
            self.atributos.append("Mais de 1/2 a 1 salários mínimos")
        elif a[2]==1:
            self.atributos.append("Mais de 1 a 2 salários mínimos")
        elif a[3]==1:
            self.atributos.append("Mais de 2 a 3 salários mínimos")
        elif a[4]==1:
            self.atributos.append("Mais de 3 a 5 salários mínimos")
        elif a[5]==1:
            self.atributos.append("Mais de 5 salários mínimos")
        else:
            self.atriburos.append("Sem declaração")

        Rede_de_ensino=[0.179, 0.821]
        cv_Rede_de_ensino=[0.119, 0.049]
        for i in range(len(cv_Rede_de_ensino)):
            Rede_de_ensino[i]=Rede_de_ensino[i]+rd.uniform(-cv_Rede_de_ensino[i]*Rede_de_ensino[i],cv_Rede_de_ensino[i]*Rede_de_ensino[i])
        b=np.random.multinomial(1,Rede_de_ensino)
        if b[0]==1:
            self.atributos.append("Pública")
        else:
            self.atributos.append("Particular")

        Dificuldade=[0.055, 0.051, 0.065, 0.039, 0.01, 0.781]
        cv_Dificuldade=[0.188, 0.195, 0.168, 0.223, 0.449, 0.051]
        for i in range(len(cv_Dificuldade)):
            Dificuldade[i]=Dificuldade[i]+rd.uniform(-cv_Dificuldade[i]*Dificuldade[i],cv_Dificuldade[i]*Dificuldade[i])
        c=np.random.multinomial(1,Dificuldade)
        if c[0]==1:
            self.atributos.append("Dificuldade financeira")
        elif c[1]==1:
            self.atributos.append("Dificuldade de acesso ao local do curso")
        elif c[2]==1:
            self.atributos.append("Dificuldade de cumprir o horário do curso")
        elif c[3]==1:
            self.atributos.append("Falta de tempo para estudar")
        elif c[4]==1:
            self.atributos.append("Outra")
        else:
            self.atributos.append("Não havia")



        Sexo=[0.562, 0.438]
        cv_Sexo=[0.051, 0.057]
        for i in range(len(cv_Sexo)):
            Sexo[i]=Sexo[i]+rd.uniform(-cv_Sexo[i]*Sexo[i],cv_Sexo[i]*Sexo[i])
        d=np.random.multinomial(1, Sexo)
        if d[0]==1:
            self.atributos.append("Homem")
        else:
            self.atributos.append("Mulher")


        Regiao=[30/477, 85/477, 245/477, 74/477, 43/477]
        cv_Regiao=[0.107, 0.084, 0.06, 0.089, 0.103]
        for i in range(len(cv_Regiao)):
            Regiao[i]=Regiao[i]+rd.uniform(-cv_Regiao[i]*Regiao[i], cv_Regiao[i]*Regiao[i])
        e=np.random.multinomial(1,Regiao)
        if e[0]==1:
            self.atributos.append("Norte")
        elif e[1]==1:
            self.atributos.append("Nordeste")
        elif e[2]==1:
            self.atributos.append("Sudeste")
        elif e[3]==1:
            self.atributos.append("Sul")
        else:
            self.atributos.append("Centro-Oeste")
            




In [73]:
x=Pessoa()
x.atributos

['Mais de 1 a 2 salários mínimos',
 'Particular',
 'Não havia',
 'Homem',
 'Sudeste']

In [46]:
a=Pessoa()



[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
